INSERT INTO Jugador VALUES (1,'pepito','1234','juan','alcachofa','jalcachofa@asdf.com','img3');
INSERT INTO Jugador VALUES (2,'jonsnow','nosabesnada','jon','snow','jsnow@asdf.com','img67');
INSERT INTO Jugador VALUES (3,'khalesi','ioquese','daenerys','targaryen','dtarga@asdf.com','img09');
INSERT INTO Jugador VALUES (4,'puto','lahorasad','david','castro','dcastro@asdf.com','img801');
INSERT INTO Jugador VALUES (5,'asdf','lkjh','asdf','ñlkj','añlkj@asdf.com','img2');
INSERT INTO Jugador VALUES (6,'elpapu','depapus','twin','lanister','tlanis@asdf.com','img407');
INSERT INTO Jugador VALUES (7,'chucknorris','addfj','carlos','norris','cnorris@asdf.com','img052');
INSERT INTO Jugador VALUES (8,'billgates','$$$$','bill','gates','bgates@asdf.com','img864');
INSERT INTO Jugador VALUES (9,'r2d2','may4th','r2','d2','rd2@asdf.com','img311');
INSERT INTO Jugador VALUES (10,'pereztroika','$$$$XD','mijail','gorvachov','mgorva@asdf.com','img93');
INSERT INTO Pegi Values(1,'3','mayores de 3');
INSERT INTO Pegi Values(2,'7','mayores de 7');
INSERT INTO Pegi Values(3,'12','mayores de 12');
INSERT INTO Pegi Values(4,'16','mayores de 16');
INSERT INTO Pegi Values(5,'18','mayores de 18');
INSERT INTO Juego VALUES (1,'dkfootball','esquiva el balon','img1',1,2);
INSERT INTO Juego VALUES (2,'dkclasico','esquiva el barril','img11',1,2);
INSERT INTO Juego VALUES (3,'dkclasico2','esquiva el barril','img2',1,2);
INSERT INTO Juego VALUES (4,'dk2edicionextendida','esquiva el barril','img21',1,2);
INSERT INTO Juego VALUES (5,'dkcollection','esquiva el barril','img0',1,2);
INSERT INTO Juego VALUES (6,'dk3','esquiva el barril','img3',1,2);
INSERT INTO Juego VALUES (7,'dk3.1','esquiva el barril','img31',1,2);
INSERT INTO Juego VALUES (8,'dk1remastered','esquiva el barril','img12',1,2);
INSERT INTO Juego VALUES (9,'dkmastercollection','esquiva el barril','img01',1,2);
INSERT INTO Juego VALUES (10,'dk4','esquiva el barril','img4',1,2);
INSERT INTO Categoria Values(1,'plataforma','asdf');
INSERT INTO Categoria Values(2,'rpg','lñkjh');
INSERT INTO Categoria Values(3,'hack n slash','qwert');
INSERT INTO Categoria Values(4,'shoter','poiuy');
INSERT INTO Categoria Values(5,'arcade','uvuwev osas');
INSERT INTO Juego_Categoria Values(1,1,1);
INSERT INTO Juego_Categoria Values(2,1,5);
INSERT INTO Juego_Categoria Values(3,2,1);
INSERT INTO Juego_Categoria Values(4,2,5);
INSERT INTO Juego_Categoria Values(5,3,1);
INSERT INTO Juego_Categoria Values(6,3,5);
INSERT INTO Juego_Categoria Values(7,4,1);
INSERT INTO Juego_Categoria Values(8,4,5);
INSERT INTO Juego_Categoria Values(9,5,1);
INSERT INTO Juego_Categoria Values(10,5,5);
INSERT INTO Juego_Categoria Values(11,6,1);
INSERT INTO Juego_Categoria Values(12,6,5);
INSERT INTO Juego_Categoria Values(13,7,1);
INSERT INTO Juego_Categoria Values(14,7,5);
INSERT INTO Juego_Categoria Values(15,8,1);
INSERT INTO Juego_Categoria Values(16,8,5);
INSERT INTO Juego_Categoria Values(17,9,1);
INSERT INTO Juego_Categoria Values(18,9,5);
INSERT INTO Juego_Categoria Values(19,10,1);
INSERT INTO Juego_Categoria Values(20,10,5);